Pages/ContactRequest.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

public class ContactRequestModel : PageModel {
    [BindProperty]
    public UserContact userContact {set; get;}

    private readonly ILogger<ContactRequestModel> _logger;
    public ContactRequestModel(ILogger<ContactRequestModel> logger){
        _logger = logger;
        _logger.LogInformation("Init contact");
    }

    public double Tong(double a, double b)
    {
        return a + b;
    }

    public void OnPost(){
        Console.WriteLine(this.userContact.Email);
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using System.ComponentModel;
using AppRazor.models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace AppRazor.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    private readonly AppDBContext _myBlogContext;

    public IndexModel(ILogger<IndexModel> logger, AppDBContext myBlogContext)
    {
        _logger = logger;
        _myBlogContext = myBlogContext;
    }

    public IActionResult OnPost()
    {
        var username = this.Request.Form["username"];
        var message = new MessagePage.Message();
        message.title = "Thông báo";
        message.htmlcontent = $"Cảm ơn {username} đã gửi thông tin";
        message.secondwait = 3;
        message.urlredirect = Url.Page("Privacy");

        // Pass the 'message' object to the ViewComponent
        return ViewComponent("MessagePage", message);
    }


    public void OnGet()
    {
        var posts = (from a in _myBlogContext.articles 
                    orderby a.Created descending
                    select a).ToList();
        ViewData["posts"] = posts;
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppRazor.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/ProductPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppRazor.Pages
{
    public class ProductPageModel : PageModel
    {
        private readonly ILogger<ProductPageModel> _logger;
        public readonly ProductService _productService;

        public ProductPageModel(ILogger<ProductPageModel> logger, ProductService productService){
            _logger = logger;
            _productService = productService;
        }

        public Product product {set; get;}
        public void OnGet(int? id)
        {
            // var data = this.Request.Query["id"];
            // if (!string.IsNullOrEmpty(data)) 
            // {
            //     Console.WriteLine(data.ToString());
            //     int i = int.Parse(data.ToString());
            // }
            
            if (id != null)
            {
                ViewData["Title"] = $"San pham(ID = {id.Value})";
                product = _productService.Find(id.Value);
            } else {
                ViewData["Title"] = $"Danh sach san pham";
            }
        }

        public IActionResult OnGetLastProduct() {
            ViewData["Title"] = $"San pham cuoi";
            product = _productService.AllProducts().LastOrDefault();

            if (product != null)
            {
                return Page();
            } else
            {
                return this.NotFound();
            }
        }

        public IActionResult OnGetRemoveAll() {
            _productService.AllProducts().Clear();
            return RedirectToPage("ProductPage");
        }

        public IActionResult OnGetLoad()
        {
            _productService.LoadProducts();
            return RedirectToPage("ProductPage");
        }

        public IActionResult OnPostDelete(int? id) {
            if (id != null)
            {
                product = _productService.Find(id.Value);
                if (product != null)
                {
                    _productService.AllProducts().Remove(product);
                }
            }

            return this.RedirectToPage("ProductPage", new{id = string.Empty});
        }
    }
}

Pages/ContactRequest.cshtml
@page "/contact.html"
@model ContactRequestModel


@{
    ViewData["Title"] = "LIEN HE";
}

<h1 class="display-4">Trang lien he</h1>
<p class="lead">Dien cac thong tin lien he</p>
<hr>

<form class="bg-light p-2 m-2" method="post" asp-page="ContactRequest">
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.userContact.UserID"></label>
        <input class="form-control" asp-for="@Model.userContact.UserID" type="text" name="UserID">
        <span class="text-danger" asp-validation-for="userContact.UserID"></span>
    </div>

    <div class="mb-3">
        <label class="form-label" asp-for="@Model.userContact.Email"></label>
        <input class="form-control" asp-for="@Model.userContact.Email" type="email" name="Email">
        <span class="text-danger" asp-validation-for="userContact.Email"></span>
    </div>

    <div class="mb-3">
        <label class="form-label" asp-for="@Model.userContact.UserName"></label>
        <input class="form-control" asp-for="@Model.userContact.UserName" type="text" name="UserName">
        <span class="text-danger" asp-validation-for="userContact.UserName"></span>
    </div>

    <button type="submit" class="btn btn-danger">Gui</button>

</form>

<div class="alert alert-danger">
    <p>Thong tin User</p>
    <ul>
        <li>UserID: @Model.userContact.UserID</li>
        <li>Email: @Model.userContact.Email</li>
        <li>Username: @Model.userContact.UserName</li>
    </ul>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/Index.cshtml
@page
@using AppRazor
@model IndexModel
@using AppRazor.models
@addTagHelper *, AppRazor
@{
    ViewData["Title"] = "Home page";
    ViewData["titlemessage"] = "New Product";
    ViewData["content"] = "You are watching new products";

    var posts = ViewData["posts"] as List<Article>;

}

<form method="post">
    <label for="">Enter your name</label>
    <input name="username" type="text">
    <input type="submit" value="Send">
</form>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>



@await Html.PartialAsync("_Message")
@await Component.InvokeAsync("ProductBox", false)

@{
    var product1 = new Product() {Name = "Iphone 14", Description = "Apple", Price = 1600};
    var product2 = new Product() {Name = "Iphone 13", Description = "Apple", Price = 1200};
    var product3 = new Product() {Name = "Samsung Edge", Description = "Samsung", Price = 900};
    var product4 = new Product() {Name = "Oppo", Description = "Oppo", Price = 700};

}
<div class="row bg-info">
    <div class="col">
        <partial name = "_ProductItem" model="product1"/>
    </div>
    <div class="col">
        @await Html.PartialAsync("_ProductItem", product2)
    </div>
    <div class="col">
        @{
            await Html.RenderPartialAsync("_ProductItem", product3);
        }
    </div>
</div>

<div class="row bg-warning">
    @{
    var products = new List<Product>(){
        new Product() {Name = "SP1", Description = "Apple", Price = 1600},
        new Product() {Name = "SP2", Description = "Apple", Price = 1200},
        new Product() {Name = "SP3", Description = "Samsung", Price = 900},
        new Product() {Name = "SP4", Description = "Oppo", Price = 700},
    };
    
    foreach (var item in products)
    {
        <div>
            <partial name = "_ProductItem" model="item"/>
        </div>
    }

}
</div>
<a asp-page="ViewProduct" asp-route-id="3">xem sp 3</a>


@{
   var productlist = new List<String> {
        "Tên Sản phẩm 1",
        "Tên Sản phẩm 2",
        "Tên Sản phẩm 3"
     };
}

<mylist
    list-title="Danh sach san pham"
    list-items="@productlist">
</mylist>

<ol>
    @foreach (var item in posts)
    {
        <li>@item.Title</li>
    }
</ol>

Pages/ProductPage.cshtml
@page "/product/{id:int?}"
@model AppRazor.Pages.ProductPageModel
@{
    var product = Model.product;
    var products = Model._productService.AllProducts();

    <h1>@ViewData["Title"]</h1>
}

@if (product != null)
{
    <h2>@product.Name</h2>
    <p>Mo ta: @product.Description</p>
    <p>Gia: @product.Price</p>

    <p>
        <a asp-page="ProductPage" asp-route-id="">Danh sach san pham</a>
    </p>
    <form method="post" asp-page="ProductPage" asp-page-handler="delete" asp-route-id ="@product.Id">
        <button type="submit" class="btn btn-danger">Xoa</button>

    </form>
}else {
    <p>Tong so SP: @products.Count</p>
    <ul>
        @foreach (var item in products)
        {
            <li>
                <a asp-page="ProductPage" asp-route-id="@item.Id">@item.Name</a>
            </li>
        }
    </ul>
    <hr>
    <p>
        <a class="btn btn-primary" asp-page="ProductPage" asp-page-handler="lastproduct">San pham cuoi</a>
        <a class="btn btn-danger" asp-page="ProductPage" asp-page-handler="RemoveAll">Xoa tat ca SP</a>
        <a class="btn btn-danger" asp-page="ProductPage" asp-page-handler="Load">Nap san pham</a>
    </p>
}

Pages/_ProductItem.cshtml
@using AppRazor
@model Product

<div class="card my-4" style="width: 20rem;">
    <h2 class="card-header text-info">@Model.Name</h2>
    <div class="card-body">
        <p class="card-text">@Model.Description</p>
        <p>Gia: @Model.Price</p>
        <a href="" class="btn btn-secondary btn-sm">Add</a>
    </div>
</div>